### PR TITLE
Add a test for a longer string, and fix support for long strings

### PR DESCRIPTION
**Pull request by prozacchiwawa**
Long strings (greater than 64 bytes) didn't match the real sha output.

For the current master, the hash of my test string, "================================66666666666666666666666666666666Hi there"
was
7489407c7b755aad41b8137cf42fde887b4e74a2b3d783d05e7983fd695a2d47

But the real sha256 produces
aeb9f11dc6622b458bae03d326d231039483c26cc1acce2b80a12c71a9fbdcdb

The problem was that the analog of https://github.com/emn178/js-sha256/blob/master/src/sha256.js#L226 in outerLoop didn't affect the next iteration so first was always True in jLoop2.

After this is corrected, I get the proper sha256 and sha224 hashes for my test string.

### CODE REVIEW

**Comment by billstclair** [comment]
I pushed the fix to the repository as version 1.0.7.

**Comment by billstclair** [comment]
Note that your new test was missing a close paren, but I fixed that after doing the merge and before pushing to the repository.

**Comment by prozacchiwawa** [comment]
Sorry for the misformatting in the test.  Thanks for taking a peek.

**Comment by billstclair** [comment]
Thank YOU for the fix.

**Pull request merged**
